// Message_Mock.js

export const user = {
  id: 0,
  name: "John Anderson",
  avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  online: true,
};

export const messages = [
  {
    id: 1,
    name: "Emily Carter",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    message: "Hey, are you coming to the meeting later today?",
    timestamp: "2 mins ago",
    online: true,
  },
  {
    id: 2,
    name: "Michael Thompson",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    message: "Just finished the presentation!",
    timestamp: "10 mins ago",
    online: false,
  },
  {
    id: 3,
    name: "Sarah Williams",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    message: "Can we reschedule our call?",
    timestamp: "30 mins ago",
    online: true,
  },
  {
    id: 4,
    name: "Daniel Moore",
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    message: "Let’s catch up tomorrow.",
    timestamp: "1 hour ago",
    online: false,
  },
  {
    id: 5,
    name: "Jessica Brown",
    avatar: "https://randomuser.me/api/portraits/women/77.jpg",
    message: "Sent you the files on Slack.",
    timestamp: "1 hour ago",
    online: true,
  },
  {
    id: 6,
    name: "William Scott",
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    message: "See you at the event later!",
    timestamp: "2 hours ago",
    online: true,
  },
  {
    id: 7,
    name: "Olivia Taylor",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    message: "Thanks for your help earlier.",
    timestamp: "3 hours ago",
    online: false,
  },
  {
    id: 8,
    name: "James Wilson",
    avatar: "https://randomuser.me/api/portraits/men/82.jpg",
    message: "Where are we meeting again?",
    timestamp: "Yesterday",
    online: true,
  },
  {
    id: 9,
    name: "Grace Martin",
    avatar: "https://randomuser.me/api/portraits/women/88.jpg",
    message: "Got your email, replying soon.",
    timestamp: "Yesterday",
    online: false,
  },
  {
    id: 10,
    name: "Henry Clark",
    avatar: "https://randomuser.me/api/portraits/men/38.jpg",
    message: "Don’t forget the meeting at 4 PM.",
    timestamp: "2 days ago",
    online: true,
  },
  {
    id: 11,
    name: "Chloe Lewis",
    avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    message: "Lunch tomorrow?",
    timestamp: "2 days ago",
    online: true,
  },
  {
    id: 12,
    name: "Logan Walker",
    avatar: "https://randomuser.me/api/portraits/men/53.jpg",
    message: "I’ll send the final draft tonight.",
    timestamp: "3 days ago",
    online: false,
  },
  {
    id: 13,
    name: "Zoe Harris",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    message: "Let’s plan the weekend trip.",
    timestamp: "3 days ago",
    online: true,
  },
  {
    id: 14,
    name: "Benjamin Hall",
    avatar: "https://randomuser.me/api/portraits/men/26.jpg",
    message: "Thanks for reviewing the document.",
    timestamp: "4 days ago",
    online: false,
  },
  {
    id: 15,
    name: "Sophia Allen",
    avatar: "https://randomuser.me/api/portraits/women/55.jpg",
    message: "Loved the designs you shared!",
    timestamp: "5 days ago",
    online: true,
  }
];
