export const MyOrderData = [
  {
    id: 1,
    name: "Eco-Friendly Yoga Mat",
    quantity: 1,
    price: 40.0,
    image: "https://via.placeholder.com/150",
    status: "Delivered",
    orderDate: "2024-10-12",
    countryOfOrigin: "China",
    countryOrderedFrom: "USA",
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    quantity: 1,
    price: 80.0,
    image: "https://via.placeholder.com/150",
    status: "Shipped",
    orderDate: "2024-10-15",
    countryOfOrigin: "Germany",
    countryOrderedFrom: "UK",
  },
  {
    id: 3,
    name: "Smartphone Stand",
    quantity: 2,
    price: 20.0,
    image: "https://via.placeholder.com/150",
    status: "Delivered",
    orderDate: "2024-10-20",
    countryOfOrigin: "South Korea",
    countryOrderedFrom: "Canada",
  },
];
